name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          sudo apt update

          sudo apt install astyle cmake gcc ninja-build libssl-dev python3-pytest python3-pytest-xdist unzip xsltproc doxygen graphviz python3-yaml valgrind

      - name: Download and build liboqs
        run: |
          git clone --depth=1 https://github.com/open-quantum-safe/liboqs
          cmake -S liboqs -B liboqs/build -DBUILD_SHARED_LIBS=ON
          cmake --build liboqs/build --parallel 8
          cmake --build liboqs/build --target install
          
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

      - name: Download and build and liboqs-python
        run: |
          git clone --depth=1 https://github.com/open-quantum-safe/liboqs-python
          cd liboqs-python
          pip install .
          cd ..
          rm -rf liboqs*
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest
